import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { AppProvider } from "context/AppProvider";
import Footer from "components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "غفران",
  description: "Generated by create next app",
   icons: [
    { rel: "icon", url: "/logo.svg", sizes: "64x64" },
    { rel: "icon", url: "/logo.svg", sizes: "128x128" },
    { rel: "icon", url: "/logo.svg", sizes: "256x256" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}
    >
      <body className="antialiased font-sans">
        <AppProvider>
          <Header />
          {children}
          <Footer/>
        </AppProvider>
      </body>
    </html>
  );
}
